nix-community/nixpkgs-fmt

- src/rules.rs
- test_data/fn_args_multiline.good.nix
- test_data/indented_lambda.bad.nix
- test_data/indented_lambda.good.nix
- test_data/nested_indent.good.nix
It's neat that `{` and `,` align in specific cases, but unfortunately
that forces us to indent arguments too much in cases like this:
```
fooo = { x
, y
} :
```
closes #46
> force line break before first function argument

- Cargo.lock
- Cargo.toml
- src/rules.rs
- test_data/syntax_errors/incomplete_set.bad.nix
- test_data/syntax_errors/incomplete_set.good.nix
The bulk of work for this is in rnix, which now doesn't assume that
the tree is correct, in nixpkgs-fmt we just adapt to the new APIs
Upstream PR: https://gitlab.com/jD91mZM2/rnix/merge_requests/21
> nixpkgs-fmt is able to format incomplete code

- Cargo.lock
- Cargo.toml
- src/dsl.rs
- src/engine.rs
- src/engine/indentation.rs
- src/lib.rs
- src/pattern.rs
- src/rules.rs
- test_data/curried_fn.good.nix
- test_data/indent_let.good.nix
- test_data/top_level_with.good.nix
I've looked how Kotlin handles this and I liked the approach:
https://github.com/JetBrains/kotlin/blob/7d173ed3856e429739b55d8c3892e1b85ca41571/idea/formatter/src/org/jetbrains/kotlin/idea/formatter/KotlinCommonBlock.kt#L682-L690
The main trick they use is negative rules: "indent all children except
X". They nicely handle comments and in general simplify things a bit.
I've also added names to rules to as a step towards future debug mode,
as well as an ability to specify simple tests in-line, which should
help with long-term rule maintainability.
closes #71, #65 
prerequisite of #74
> implement new version of indentation DLS

- src/dsl.rs
- src/lib.rs
- src/rules.rs
I am somewhat :cry: to see the beautiful `include_str!()` hack go, but this is indeed a better and simpler approach :) 
bors r+
> don't use comments for spacing tests

- .pre-commit-config.yaml
- ci.sh
Format the nix code with the current version of nixpkgs-fmt instead of
master.
> pre-commit: use the current nixpkgs-fmt

- .pre-commit-config.yaml
- .pre-commit-hooks.yaml
- README.md
- src/main.rs
The --output flag was removed to handle formatting multiple files at the
same time. But since that flag is missing, it doesn't make sense to
output multiple files on stdout as well.
If the user wants to format a file and write the output to a different
place, use stdin and stdout.
> main: remove the --in-place flag

- Cargo.lock
- Cargo.toml
- src/main.rs
This might be useful to add custom post-processing to formatting.
See https://discourse.nixos.org/t/text-based-ir-for-nix-formatters/3543
<details>
<summary>Example Output</summary>
```
18:03:01|~/projects/nixpkgs-fmt|serde✓
λ cargo run -- --parse --json --pretty < ~/tmp/ex.nix
Compiling nixpkgs-fmt v0.1.0 (/home/matklad/projects/nixpkgs-fmt)
Finished dev [unoptimized + debuginfo] target(s) in 0.92s
Running `target/debug/nixpkgs-fmt --parse --json --pretty`
{
"kind": "NODE_ROOT",
"text_range": [
0,
8
],
"children": [
{
"kind": "NODE_OPERATION",
"text_range": [
0,
8
],
"children": [
{
"kind": "NODE_LIST",
"text_range": [
0,
2
],
"children": [
{
"kind": "TOKEN_SQUARE_B_OPEN",
"text_range": [
0,
1
],
"text": "["
},
{
"kind": "TOKEN_SQUARE_B_CLOSE",
"text_range": [
1,
2
],
"text": "]"
}
]
}, …
```
> Add ability to print syntax tree in JSON format

- Cargo.lock
- Cargo.toml
- src/lib.rs
For using this in a library, it would be great to have the original
diff available. Example usecase is embedding this inside rnix-lsp
without sending the entire file back, but rather just the areas that
were changed.
> Expose diff function

- src/main.rs
> replace #[macro_use] extern crate with modern syntax

- src/dsl.rs
- src/engine.rs
- src/engine/fmt_model.rs
- src/engine/indentation.rs
- src/engine/spacing.rs
- src/lib.rs
- src/main.rs
- src/rules.rs
This implements the basic scaffold for explain mode, which prints original source code with the names of the rules which caused whitespace changes. 
I didn't try to do anything fancy here, just print the changes next to the changed lines. We might investigate https://docs.rs/annotate-snippets/0.6.1/annotate_snippets/ in the future, if we want something nicer.
Note that at the moment only indent ruels are named
> Explain mode

- nix/sources.json
This updated version of `naersk` contains https://github.com/nmattia/naersk/commit/5958f39351c94b0638c0bd83a684cfab7a4e74e6, which uses `builtins.pathExists` on Nix v2.3+. As a result, projects using `lorri` can use `nixpkgs-fmt` without triggering the problematic behaviour described in this issue report: https://github.com/target/lorri/issues/237.
> Update nearsk dependency

- default.nix
My PR https://github.com/nix-community/nixpkgs-fmt/pull/153 just broke the build. I'm really sorry about that. This fixes it.
Context: the nearsk `buildPackage` function now takes arguments differently: https://github.com/nmattia/naersk/commit/4714fb8ac180e72facffa42dd652ed460b07d9aa
> Fix Nix build

- nix/sources.json
The latest versions of naersk don't build the documentation by default,
which speeds up the build a fair bit.
> nix: update naersk

- flake.nix
- src/rules.rs
- test_data/curried_fn_no_indent.good.nix
- test_data/indent_paren.bad.nix
- test_data/indent_paren.good.nix
- test_data/issue-125.bad.nix
- test_data/issue-125.good.nix
- test_data/issue-151.bad.nix
- test_data/issue-151.good.nix
- test_data/issue-152.bad.nix
- test_data/issue-152.good.nix
This PR fixes:
1. Indentation inside function body (lambda pattern);
2. Additional test data on `let .. in` to fit the indentation problem inside parenthesis. This is a good fix actually, because it avoids too much rule with regard to indentation.
3. Adjust flake.nix with the new indentation of body function rule.
> fix #151 function body indent and small fix on let ... in

- src/rules.rs
- test_data/issue-161.bad.nix
- test_data/issue-161.good.nix
This PR only force linebreak if after the apply function exists parenthesis. The curly bracket will remain inline.
> Fix #161: Align the function apply with the attribute set

- src/engine.rs
- src/rules.rs
- test_data/issue-158.bad.nix
- test_data/issue-158.good.nix
Note: In addition to #158, node `if .. else` will not be expanded if `if .. else` is after `in` token.
> Fix #158 spacing and indentation on node if then else

- src/rules.rs
- test_data/issue-181.bad.nix
- test_data/issue-181.good.nix
This PR try to make parentheses more relax on forcing newline before close parentheses.
> Fix #181: remove forcing newline before close parentheses

- src/engine.rs
- src/engine/fixes.rs
- src/engine/indentation.rs
- test_data/indent_string_literal_interpolation.bad.nix
- test_data/indent_string_literal_interpolation.good.nix
This PR try to solve antiquotation inside `NODE_STRING`. What I am doing in this PR are:
1. looping inside `NODE_STRING_INTERPOL` and apply `set_indent` based on the element`s `anchor`. This is actually work similar to `apply` function for rules.
2. Due to slightly different approach from the `apply` function, the `string_interpol_indent` function has to make additional case for `TOKEN_THEN` and `TOKEN_THEN`. I am not sure if there is any other case that has to be addressed like in `NODE_IF_ELSE`. If too many node/token that should be address in `string_interpol_indent` function, then I have to make it separate function.
> Fix: #166 and #175 - antiquotation in multiline string

- src/rules.rs
Violating idempotence highlights a bigger bug than just a wrong
formatting.
r? @Rizary, that's what we've discussed during the call. I've checked, and commenting out half of `"Indent newline lambda body"` indeed fails this check
> Check idempotence beftore expected

- src/engine.rs
- src/rules.rs
@Rizary do you remmember why we need `common_binops`? seems like current tests do not expose the need for it. If we do need them, I'd express them as declarative token set, similar to `BIN_OPS`, rather than as a separate function.
> Remove some dead code

- src/rules.rs
That's just a syntactic change, but I think it makes the code a tad more readable.
> Use T! macro for symbolic tokens

- src/engine.rs
- src/engine/fixes.rs
- src/engine/indentation.rs
- src/tree_utils.rs
- test_data/indent_string_literal_interpolation.bad.nix
- test_data/indent_string_literal_interpolation.good.nix
- test_data/issue-199.bad.nix
- test_data/issue-199.good.nix
- test_data/nixpkgs_repository/lib_strings.good.nix
- test_data/nixpkgs_repository/nixos_lib_testing_python.good.nix
- test_data/nixpkgs_repository/nixos_modules_config_console.good.nix
This is an approach alternative to #213.
Here, the idea is that we indent string block as a whole, without
looking into it contents at all. To that end we:
* introduce `walk_non_whitespace_non_interpol` funciton, which walks
the tree skipping interpolated nodes
* tweak `node_indent_ranges` to also just shift stuff inside
intepolated fragments
* remove existing depth-based interpolation strategy
> Alternative interpolation indentation strategy

- flake.nix
This is deprecated per https://github.com/NixOS/nixpkgs/issues/108938.
> flake: use `lib` instead of `stdenv.lib`

- src/engine.rs
- src/rules.rs
- src/tree_utils.rs
- test_data/indent_string_literal_interpolation.bad.nix
- test_data/indent_string_literal_interpolation.good.nix
- test_data/issue-125.good.nix
- test_data/nixpkgs_repository/nixpkgs_idempotent.bad.nix
- test_data/nixpkgs_repository/nixpkgs_idempotent.good.nix
This PR does fix reformatting issue with nixpkgs repository by fixing the following:
1.  add format rule for `NODE_OR_DEFAULT`
2. add adding nixpkgs repository test called `nixpks_idempotent.<bad/good>.nix` 
3. remove function `walk_non_whitespace` when apply the spacing rules and use `walk_non_whitespace_non_interpol` instead.
> Remove formatting twice on nixpkgs repository

- README.md
- src/main.rs
part of issue https://github.com/nix-community/nixpkgs-fmt/pull/101#issuecomment-824185560
<details>
<summary>test</summary>
```
./target/debug/nixpkgs-fmt --parse --output-format json <( echo null ) | head -n6
{
"kind": "NODE_ROOT",
"text_range": [
0,
5
],
./target/debug/nixpkgs-fmt --parse --output-format rnix <( echo null ) | head -n1
NODE_ROOT 0..5 {
./target/debug/nixpkgs-fmt --help 2>&1 | grep output-format
--output-format <FORMAT>    Set output format of --parse [default: rnix]  [possible values: rnix, json]
./target/debug/nixpkgs-fmt --parse --output-format invalid-format <( echo null )
error: 'invalid-format' isn't a valid value for '--output-format <FORMAT>'
[possible values: json, rnix]
```
</details>
<details>
<summary>javascript snippet</summary>
```js
// javascript: parse …
```
> fix CLI option output-format

- Cargo.lock
- Cargo.toml
- src/main.rs
- tests/integration_tests.rs
Commands that print their results to stdout should terminate on `SIGPIPE`, so that they don't produce error messages when piped into programs like `head` or `less` that might exit before the process is finished.  This is the default behaviour on Unix, but the Rust runtime ignores `SIGPIPE` by default.
For nixpkgs-fmt modes where it makes sense, re-enable the Unix default behaviour of terminating on `SIGPIPE`.  Don't do this when formatting files, because only formatting half the files if stdout was closed would be a surprising behaviour.
> Properly handle SIGPIPE

- Cargo.lock
- default.nix
- flake.lock
- flake.nix
Upstream fenix has changed. Bump all the dependencies and fix the build
issues.
Fixes #257
> flake update

- README.md
See also https://github.com/nix-community/nixpkgs-fmt/issues/157. For users like myself, VSCode extensions are the primary way that I interact with a tool like nixpkgs-fmt. I figure we might as well advertise these sister projects to promote the usage of nixpkgs-fmt.
> Add links to VSCode extensions to README

- Cargo.lock
- Cargo.toml
Needed to release `rnix-lsp`[1] with a newer `rnix` later on.
Changes: https://github.com/nix-community/rnix-parser/blob/cd7a310f7a7b87d3afe8ed6703d92e6554de67ab/CHANGELOG.md
[1] https://github.com/nix-community/rnix-lsp
> Update `rnix` to 0.10.1

- src/rules.rs
- Avoid the following warning:
```
warning: panic message is not a string literal
--> src/rules.rs:815:29
|
815 |         .map_err(|e| panic!(e))
|                             ^
|
= note: `#[warn(non_fmt_panics)]` on by default
= note: this usage of panic!() is deprecated; it will be a hard error in Rust 2021
= note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/panic-macro-consistency.html>
help: add a "{}" format string to Display the message
|
815 |         .map_err(|e| panic!("{}", e))
|                             +++++
```
> refactor: avoid non_fmt_panics warning

- src/engine.rs
- src/lib.rs
This pull request exposes a function which returns the spacing edits and indentation edits required to reformat the given node. I'd like to do this so that `rnix-lsp` (which uses this crate), can respond to document formatting requests with multiple small edits instead of responding with one huge edit that replaces the entire document.
I am somewhat unsure of what type these edits should be returned as. Please see the description of the related `rnix-lsp` pull request ([rnix-lsp#87](https://github.com/nix-community/rnix-lsp/pull/87)) for a discussion of that.
> feat: add `reformat_edits` function
