nix-community/nixpkgs-fmt

- shell.nix
> Add missing framework on Darwin

- src/rules.rs
- test_data/semicolon_in_set.bad.nix
- test_data/semicolon_in_set.good.nix
> tweak semicolon placement in attrs

- Cargo.lock
> :arrow_up: rnix

- src/dsl.rs
- src/rules.rs
> deduplicate operator rules

- Cargo.lock
- src/dsl.rs
- src/rules.rs
> use T macro from rnix

- .travis.yml
- ci.sh
- deploy.sh
Publish the WASM project to github pages
> WASM GitHub pages

- deploy.sh
and also simplify the no-commit logic a bit
fixes #30
> deploy: fix missing pkg

- src/rules.rs
> show all failed tests at once

- src/dsl.rs
- src/engine.rs
- src/lib.rs
- src/pattern.rs
Extract predicates from engine, add comments and use asymptotically more efficient matching algorithm. 
bors r+
> Refactor predicate handling

- src/engine.rs
- src/engine/fmt_model.rs
- src/engine/indentation.rs
> Refactor indentation handling

- src/rules.rs
- test_data/nested_indent_after_binop.bad.nix
- test_data/nested_indent_after_binop.good.nix
> indent binops relative to right hand side

- src/lib.rs
This way, code can assume that line endings are always `\n`, which
simplifies things a great deal!
> preserve line ending flavor when reformatting

- src/rules.rs
- test_data/if_then_else_indent.bad.nix
- test_data/if_then_else_indent.good.nix
> indent if expression

- src/engine.rs
- src/rules.rs
- test_data/indent_paren.bad.nix
- test_data/indent_paren.good.nix
> Indent parens

- Cargo.lock
- src/dsl.rs
- src/engine.rs
- src/engine/fixes.rs
- src/engine/fmt_model.rs
- src/engine/indentation.rs
- src/engine/spacing.rs
- src/lib.rs
- src/pattern.rs
- src/rules.rs
- src/tree_utils.rs
The primary change here is that nodes are no longer references with
lifetime, but rather reference-counted owned objects.
bors r+
> Migrate to the new rowan/rnix

- src/dsl.rs
- src/lib.rs
- src/rules.rs
> If then else spacing

- README.md
- nix/sources.json
- nix/sources.nix
- shell.nix
> Add `cargo fuzz` to the CI

- .pre-commit-config.yaml
- README.md
- ci.sh
- shell.nix
- src/lib.rs
- src/tree_utils.rs
Add pre-commit to the project so we keep the syntax nicely formatted.
This is a bit of a warmup. Once https://github.com/pre-commit/pre-commit/issues/1112 is fixed it will be possible to expose nixpkgs-fmt as a pre-commit hook as well!
> pre-commit

- .pre-commit-config.yaml
- .pre-commit-hooks.yaml
- README.md
- nix/sources.json
- shell.nix
- src/main.rs
After this PR this project will be usable as a pre-commit hook. I had to change the command-line to allow multiple files since I didn't find how to invoke nixpkgs-fmt once per file in pre-commit.
> Pre commit hook

- README.md
We use nightly only for running fuzzers.
r? @zimbatm
> don't ask for nightly rust

- .pre-commit-config.yaml
- shell.nix
- src/pattern.rs
- src/rules.rs
- test_data/indent_let.good.nix
- test_data/issue-83-1.good.nix
- test_data/top_level_let.bad.nix
- test_data/top_level_let.good.nix
> don't indent top-level let

- Cargo.lock
- wasm/Cargo.toml
- wasm/index.html
- wasm/src/lib.rs
> wasm: add diff output

- default.nix
- nix/nixpkgs.nix
- shell.nix
Fixes #113 
How do you feel about having to update a pair of sha256 whenever the Cargo.lock file changes @matklad ?
> add default.nix

- wasm/index.html
README says status is beta, so it needs to be updated here.
> Update Status on Demo page

- .pre-commit-config.yaml
make sure the nix code is formatted with the latest version of nixpkgs-fmt even if the code hasn't changed
> pre-commit: always run nixpkgs-fmt

- src/rules.rs
- test_data/list_with_commented_out_item.bad.nix
- test_data/list_with_commented_out_item.good.nix
> add line break after comment in list

- src/lib.rs
> convert tabs to spaces

- README.md
- default.nix
- nix/nixpkgs.nix
- nix/sources.json
- update-cargo-nix.sh
naersk is brilliant. It calculates the cargo sha256 automatically by
reading the Cargo.lock and does all the right things.
https://github.com/nmattia/naersk
Thanks @nmattia !
> nix: use naersk

- Cargo.lock
- Cargo.toml
- nix/sources.json
- shell.nix
- src/main.rs
> Nixpkgs fmt check

- src/dsl.rs
- src/engine/fixes.rs
- src/engine/indentation.rs
- src/lib.rs
- src/pattern.rs
- src/tree_utils.rs
Getting my feet wet with this project, hope it looks okay :smiley:
> Fix clippy lint warnings/errors

- .travis.yml
- ci.sh
Follow-up to https://github.com/nix-community/nixpkgs-fmt/pull/154. Context: https://github.com/nix-community/nixpkgs-fmt/pull/154#issuecomment-558102318.
> Build with Nix in CI

- src/dsl.rs
- src/rules.rs
- src/tree_utils.rs
- test_data/issue-125.bad.nix
- test_data/issue-125.good.nix
> Changing SpacingDsl behavior for let ... in node

- src/dsl.rs
- src/rules.rs
- src/tree_utils.rs
- test_data/curried_fn.good.nix
- test_data/issue-125.bad.nix
- test_data/issue-125.good.nix
- test_data/issue-83-2.good.nix
This PR is a WIP which try to fix #125 and #167 
I have change the possible `let ... in ` syntax that I learn based on `test_data` folder.
> Fixing formatting on let in notation

- nix/nixpkgs.nix
- src/engine.rs
- src/rules.rs
- src/tree_utils.rs
- test_data/issue-126.bad.nix
- test_data/issue-126.good.nix
This PR will fix list item and parentheses
> Fix #126: parentheses and list element rules

- README.md
I whipped up Emacs support for this, soon to appear in MELPA.
> Mention emacs-nixpkgs-fmt

- src/engine.rs
- src/lib.rs
The biggest issue with our current formatting infra is that patterns
are evaluated on the original syntax tree, and not on the formatting
model, which might contain whitespace changes.
A particular bad issue here is when whitespace changes add or remove
newlines, but then we use newline info to calculate indent.
Originally, the thinking was that this is not necessary, as rules
would only depend on the shape of the tree and not on the spacing, but
turns out this is not the case in practice.
The "obvious" fix here is to make our formatting model & predicated
more complicated, so that they can take modified whitespace into
account. But this PR proposes something more stupid, yet more
elegant (subjectively) -- we just commit whitespace changes to the
syntax tree before re-indent pass.
That …
> Experiment: commit whitespace changes before computing indentation.

- src/rules.rs
- src/tree_utils.rs
- test_data/indent_lambda_top_level.bad.nix
- test_data/indent_lambda_top_level.good.nix
> Remove indentation for lambda function in top level

- src/engine/fixes.rs
- src/engine/indentation.rs
- test_data/reindents_block_comments.bad.nix
- test_data/reindents_block_comments.good.nix
> fix multiline comment

- src/engine/fixes.rs
- src/engine/indentation.rs
- src/rules.rs
- src/tree_utils.rs
- test_data/curried_fn.good.nix
- test_data/nixpkgs_repository/lib_attrset.good.nix
- test_data/nixpkgs_repository/lib_deprecated.good.nix
- test_data/nixpkgs_repository/lib_modules.good.nix
- test_data/nixpkgs_repository/nixos_lib_testing_python.good.nix
there are changes in the test_data to match the output. Please bear in mind that we calculate the format based on the input.
> Let idempotent

- src/main.rs
This changes the behavior of `nixpkgs-fmt --parse` to emit errors to
stderr and to exit with an error code when any errors are found.
Close #267
> improve error CLI ergonomics

- default.nix
- flake.lock
- flake.nix
Just to collapse the dependency tree.
> nix: remove naersk
